image: "gitlab-registry.cern.ch/fitters/xfitter"

cache:
  paths:
    - deps

stages:
  - build

before_script:
  - yum -y install yum-plugin-ovl
  - yum -y install which yaml-cpp-devel libyaml-devel gsl-devel cmake git 
  - . ./scripts/setup.sh
  - ./scripts/install-deps.sh

job-install:
  stage: build
  only: [merge_requests]
  script: 
    - ./make.sh install
    - git clone https://gitlab.cern.ch/ozenaiev/xfitter-datafiles.git temp-datafiles
    - mv temp-datafiles/.git datafiles/.git
    - rm -rf temp-datafiles
    - cd datafiles
    - git reset --hard HEAD
    - cd -
    - lhapdf --source=http://lhapdfsets.web.cern.ch/lhapdfsets/current/ install CT10 HERAPDF20_NNLO_EIG HERAPDF20_NNLO_VAR CT14nnlo ABMP16_3_nlo HERAPDF20_NLO_FF3B_EIG NNPDF31_nlo_as_0118_hessian MMHT2014nnlo68cl 
    - ./tools/test.sh
  variables:
    CMAKE_FLAGS: "-DCMAKE_DISABLE_FIND_PACKAGE_ROOT=TRUE" 

#nightly_devel:
#  stage: nightly
#  script:
#    - ./scripts/test-build.sh
#    - ./scripts/test-build.sh apfel applgrid lhapdf
#  only:
#    - devel
#    - triggers
