image: "gitlab-registry.cern.ch/fitters/xfitter"

cache:
  paths:
    - deps

stages:
  - build

before_script:
  - yum -y install yum-plugin-ovl
  - yum -y install which yaml-cpp-devel libyaml-devel gsl-devel cmake
  - . ./scripts/setup.sh
  - ./scripts/install-deps.sh

job-install:
  stage: build
  only: [merge_requests]
  script: "./make.sh install"
  variables:
    CMAKE_FLAGS: "-DCMAKE_DISABLE_FIND_PACKAGE_ROOT=TRUE" 

#nightly_devel:
#  stage: nightly
#  script:
#    - ./scripts/test-build.sh
#    - ./scripts/test-build.sh apfel applgrid lhapdf
#  only:
#    - devel
#    - triggers
