Minimizer: MINUIT
MINUIT:
  doErrors: None #Pumplin #Hesse
  Commands: |
    minimize
    call fcn 3
    #hesse
    #fix 103 106 107 109 111 112 113 114 115 116 117 118 119 120 122

Parameters:
  Av: DEPENDENT
  Bv: [ 0.8015, 0.1]
  Cv: [ 1.0105, 0.1]
  As: [ 0.0818, 0]
  Bs: [-0.2   , 0]
  Cs: [ 8     , 0]
  Ag: DEPENDENT
  Bg: [0,0]
  Cg: [9,0]
  M:  [1.225,0] #additional scaling of predictions
Parameterisations:
  v:
    class: HERAPDF
    parameters: [Av,Bv,Cv]
  S:
    class: HERAPDF
    parameters: [As,Bs,Cs]
  g:
    class: HERAPDF
    parameters: [Ag,Bg,Cg]

Decompositions:
  pion:
    class: SU3_Pion
    valence: v
    sea: S
    gluon: g

Evolutions:
  pion:
    ? !include yaml/evolutions/QCDNUM/parameters.yaml
    decomposition: pion
  tungsten_target:
    class: LHAPDF
    set:   nCTEQ15FullNuc_184_74
    member: 0
  GRV:
    class: LHAPDF
    set:   GRVPI0
    member: 0
DefaultEvolution: pion

Q0: 1.378404875209022   #=sqrt(1.9)
alphas: 0.118
fs: 0.3333333 #this is not actually used by decomposition

byReaction:
  APPLgrid:
    ? !include yaml/reactions/APPLgrid/parameters.yaml
    evolution1: pion
    #evolution1: GRV
    evolution2: tungsten_target
    scaleParameter: M

Profiler:
  alphas: [ 0.118, 0.119, 0.117 ]
# Evolutions:
#   tungsten_target:
#     sets:    [nCTEQ15FullNuc_184_74]
#     members: [[0,1,end]]

? !include constants.yaml
