#
# Test file to illustrate how parameters can be transferred
#

# include : test.yaml  # Can include any file

Mz : 91.1876
Mw : 80.384

gf : 1.16638e-5

convFac : 0.389379338e9

sin2thW : 
  value : 0.23127
  step  : 0.0

Order : NLO
NFlavour : 5

mch : 1.43 
mbt : 4.5


# Optimal RT scheme:
RT_DISNC:               # Reaction-specific settings
  varin : [0.0, 1.0, -0.666666666667, 1.0]

# FF ABM scheme
# runm: 0 for pole mass (default); 1 for MSbar running mass
# ordfl: 1 for O(alpha_S) in F_L = O(alpha_S) + 1 in F_2 (default); 0 for O(alpha_S) in F_L = O(alpha_S) in F_2
# renormalisation and factorisation scale for HQs set via parameters:  mu^2 = scalea1 * Q^2 + scaleb1 * 4*m_h^2 (default scalea1 = scaleb1 = 1.0)
FFABM_DISNC:
  runm: 1
  ordfl: 1
  scalea1: 1.0
  scaleb1: 1.0

# speficify HF scheme:
hf_scheme_DISNC : 
  value : 'RT_DISNC'
#  value : 'FFABM_DISNC'
#  'HERA1+2 NCep 920' : 'BaseDISNC'
#  1 : BaseDISNC  


hf_scheme_DISCC :
  value : 'BaseDISCC'

# We want to fit alphaS, making this explicitly:
AalphaS: 
  value: 20.0
  step:  0.0
  prior: 20.0  
  priorUnc: 0.1
  min: 19.0
  max: 21.0


APPLgrid:  # APPLgrid specific
  muF: 1.0
  muR: 1.0
  Order : NLO   # APPLgrids are at max. NLO for now

# Example of vectors

testVec :  [1., 2., 3., 4.]

Fractal_DISNC :
  D0 : 
    value : 0.75
    step  : 0.01
  Q02 :
    value : 0.093
    step  : 0.01
  D1 :
    value : 0.052
    step  : 0.01
  D2 :
    value : 1.08
    step  : 0.01
  D3 :
    value : -1.16
    step  : 0.01
  R :
    value : 0.56
    step  : 0.01
