#
# Test file to illustrate how parameters can be transferred
#

Mz : 91.1876
Mw : 80.385
sin2thW : 
  value : 0.23127
  step  : 0.00

Order : NLO
NFlavour : 5

mch : 1.43 
mbt : 4.5

# Optimal RT scheme:
varin : [0.0, 1.0, -0.666666666667, 1.0]

# speficify HF scheme:
hf_scheme_DISNC : 
  value : 'TensorPomeron'
#  'HERA1+2 NCep 920' : 'BaseDISNC'
#  1 : BaseDISNC  

# We want to fit alphaS, making this explicitly:
AalphaS: 
  value: 20.0
  step:  0.0
  prior: 20.0  
  priorUnc: 0.1
  min: 19.0
  max: 21.0


muF: 1.0
muR: 1.0

# Pomeron model:

s0bn : [0.35, 1.0,  3.0, 10.0, 18.0, 33.0, 45.0]
s1bn : [0.0,  0.35, 1.2,  3.5, 10.0, 45.0]
s0rn : [1.2,  8.5,  45.0 ]
s1rn : [0.25,  1.2,  8.5]

mP      : 0.938272
alphaEM : 0.0072973525664
alphaP  : 0.25
beta    : 1.87
m02     : 0.0
m12     : 0.5

# fitted parameters:

# spline b0:
s0bv0 :
  value : -5.59
  step  : 0.00
s0bv1 :
  value : -4.76
  step  : 0.00
s0bv2 :
  value : -5.09
  step  : 0.00
s0bv3 :
  value : -5.73
  step  : 0.00
s0bv4 :
  value : -6.11
  step  : 0.00
s0bv5 :
  value : -6.596
  step  : 0.00
s0bv6 :
  value : -6.892
  step  : 0.00

# spline b1:

s1bv0 : 
  value : -0.789
  step  :  0.00
s1bv1 : 
  value : -1.444
  step  :  0.00
s1bv2 : 
  value : -2.354
  step  :  0.00
s1bv3 : 
  value : -3.338
  step  :  0.00
s1bv4 : 
  value : -4.508
  step  :  0.00
s1bv5 : 
  value : -7.300
  step  :  0.00

# spline r0:
s0rv0 : 
  value : -1.12 
  step  : 0.00
s0rv1 : 
  value : -1.226
  step  : 0.00
s0rv2 : 
  value : -2.30 
  step  : 0.00

# spline r1:
s1rv0 : 
  value : -3.42 
  step  : 0.00
s1rv1 : 
  value : -1.86
  step  : 0.00
s1rv2 : 
  value : -6.1
  step  : 0.00

# slopes:

epsilon0 : 
  value : 0.310
  step  : 0.00

epsilon1 : 
  value : 0.079
  step  : 0.00

