# File to store parameters for theory modules. Overwrites
# fortran-based ewparam.txt.

#
# EW parameters
#---------------------------
Mz : 91.1876
Mw : 80.385
Mh : 125.9

Wz : 2.4952
Ww : 2.085
Wh : 1d-3
Wtp : 2.0d0

gf : 1.16638e-5
convFac : 0.389379338e9
alphaem : 7.29735e-3

sin2thW :  0.23127
Vud : 0.97427
Vus : 0.2254
Vub : 0.00358
Vcd : 0.22520
Vcs : 0.97344 
Vcb : 0.04156
Vtd : 0.00872
Vts : 0.04076
Vtb : 0.999133

#
# lepton masses:
#---------------------------
men : 1e-10
mel : 0.510998928e-3
mmn : 1e-10
mmo : 0.1056583715
mtn : 1e-10
mta : 1.77682

#
# Light quark masses:
#---------------------------
mup : 0.06983
mdn : 0.06983
mst : 0.150

#
# Heavy quark masses:
#---------------------------
mch : 1.43 
mbt : 4.50
mtp : 173.0

#
# QCD parameters
#---------------------------
Order : NNLO
NFlavour : 5

#
# AlphaS, incuding options to fit it:
#---------------------------
alphas: 0.118
#  value: 0.118
#  step:  0.0
#  prior: 0.118
#  priorUnc: 0.1
#  min: 0.1
#  max: 0.3

# Strange and charm fractions:
#---------------------------
fs: 0.4
fcharm: 0.

#
# RT DIS scheme settings:
#---------------------------
include : yaml/reactions/RT_DISNC/parameters.yaml

#
# FONLL scheme settings:
#---------------------------
include : yaml/reactions/FONLL_DISNC/parameters.yaml
include : yaml/reactions/FONLL_DISCC/parameters.yaml

# FF ABM scheme settings:
#---------------------------
include : yaml/reactions/FFABM_DISNC/parameters.yaml
include : yaml/reactions/FFABM_DISCC/parameters.yaml

#
# APPLgrid settings:
#---------------------------
include : yaml/reactions/APPLgrid/parameters.yaml

#
# (optional) Fractal module settings:
#---------------------------
# include : yaml/reactions/Fractal_DISNC/parameters.yaml

#
# Speficify HF scheme used for DIS NC processes:
#---------------------------
hf_scheme_DISNC :
  defaultValue : 'BaseDISNC'       # global specification
#  defaultValue : 'RT_DISNC'        # global specification
#  defaultValue : 'FONLL_DISNC'     # global specification
#  defaultValue : 'FFABM_DISNC'
#  'HERA1+2 NCep 920' : 'BaseDISNC' # datafile specific (based on name)
#  1 : BaseDISNC
#  'HERA1+2 NCep 920' : 'Fractal_DISNC'  # Fractal model. Add parameters file if you want to try it (see above)

#
# Speficify HF scheme used for DIS CC processes:
#---------------------------
hf_scheme_DISCC :
  defaultValue : 'BaseDISCC'       # global specification
#  defaultValue : 'FONLL_DISCC'     # global specification
#  defaultValue : 'FFABM_DISCC'     # global specification
