Minimizer: MINUIT # CERES
MINUIT:
  Commands: |
    fix 6 7 9 11 12 13 14 15 16 17 18 19 20 22 
    call fcn 3
#  doErrors :  Hesse # None

Parameters:
  Ag   :  DEPENDENT
  Bg   : [ -0.061953]
  Cg   : [  5.562367 ,  0.55]
  Agp  : [ 0.07311  ]  # negative gluon ....
  Bgp  : [ -0.383100 ]
  Cgp  : [ 25.0, 0.]  # fix C of negative gluon
  Auv  :  DEPENDENT
  Buv  : [ 0.810476 ]
  Cuv  : [ 4.823512 ]
  Duv  : [    0     ]
  Euv  : [ 9.921366 ]
  Adv  :  DEPENDENT
  Bdv  : [ 1.029995 ]
  Cdv  : [ 4.846279 ]
  Aubar: [ 0.1613    ]
  Bubar: [ -0.1273   ]
  Cubar: [ 7.059694]
  Dubar: [ 1.548098]
  Adbar: [ 0.1613    ]
  Bdbar: [ -0.1273  ]
  Cdbar:
    value: 9.586246
    step: 1.2345
    #min
    #max
    #pr_mean
    #pr_sigma
  As   : [ 0.1075    ]
  Bs   : [  -0.1273  ]
  Cs   : [ 9.586246  ]
  ZERO : [ 0. ]          # zero

Parameterisations:
  par_uv:
    class: HERAPDF
    parameters: [Auv,Buv,Cuv,Duv,Euv]
  par_dv:
    class: HERAPDF
    parameters: [Adv,Bdv,Cdv]
  par_ubar:
    class: HERAPDF
    parameters: [Aubar,Bubar,Cubar,Dubar]
  par_dbar:
    class: HERAPDF
    parameters: [Adbar,Bdbar,Cdbar]
  par_s:
    class: HERAPDF
    parameters: [As,Bs,Cs]
  par_g:
    class: NegativeGluon
    parameters: [Ag,Bg,Cg,ZERO,ZERO,Agp,Bgp,Cgp]
  #Example for Expression parameterisation
  #par_g:
  #  class: Expression
  #  expression: "Ag*(x^Bg*(1-x)^Cg-Agp*x^Bgp*(1-x)^Cgp)"

DefaultDecomposition: proton
Decompositions:
  proton:
    class: UvDvubardbars
    xuv: par_uv
    xdv: par_dv
    xubar: par_ubar
    xdbar: par_dbar
    xs: par_s
    xg: par_g

#DefaultEvolution: proton-APFELff
DefaultEvolution: proton-QCDNUM

Evolutions:
  proton-APFELff:
    ? !include evolutions/APFEL/parameters.yaml
    decomposition: proton
  proton-QCDNUM:
    ? !include evolutions/QCDNUM/parameters.yaml
    decomposition: proton #this could be omitted, as the default decomposition is set
  proton-LHAPDF:
    class: LHAPDF
    set: "CT10"
    member: 0
#  proton-APFEL:
#    ? !include yaml/evolutions/APFELxx/parameters.yaml
#    decomposition: proton
#  antiproton:
#    class: FlipCharge
#    input: proton-QCDNUM
#  neutron:
#    class: FlipUD
#    input: proton-QCDNUM

Q0 : 1.378404875209 # Initial scale =sqrt(1.9)

? !include constants.yaml

alphas : 0.118

byReaction:
  # RT DIS scheme settings:
  ? !include reactions/RT_DISNC/parameters.yaml
  # FONLL scheme settings:
  ? !include reactions/FONLL_DISNC/parameters.yaml
  ? !include reactions/FONLL_DISCC/parameters.yaml
  # FF ABM scheme settings:
  ? !include reactions/FFABM_DISNC/parameters.yaml
  ? !include reactions/FFABM_DISCC/parameters.yaml
  # AFB settings:
  ? !include reactions/AFB/parameters.yaml
  # APPLgrid settings:
  ? !include reactions/APPLgrid/parameters.yaml
  # (optional) Fractal module settings:
  # ? !include reactions/Fractal_DISNC/parameters.yaml

# Specify HF scheme used for DIS NC processes:
hf_scheme_DISNC :
  defaultValue : 'RT_DISNC'        # global specification
#  defaultValue : 'BaseDISNC'       # global specification
#  defaultValue : 'FONLL_DISNC'     # global specification
#  defaultValue : 'FFABM_DISNC'
#  'HERA1+2 NCep 920' : 'BaseDISNC' # datafile specific (based on name)
#  1 : BaseDISNC
#  'HERA1+2 NCep 920' : 'Fractal_DISNC'  # Fractal model. Add parameters file if you want to try it (see above)

# Specify HF scheme used for DIS CC processes:
hf_scheme_DISCC :
  defaultValue : 'BaseDISCC'       # global specification
#  defaultValue : 'FONLL_DISCC'     # global specification
#  defaultValue : 'FFABM_DISCC'     # global specification
