Minimizer: MINUIT

PDFDecomposition: GRV_PionPdfDecomposition
GRV_PionPdfDecomposition:
  HARDWIRED_PolySqrt: #=A*x^B*(1-x)^C*(1+D*sqrt(x)+E*x)
    v   : [0    ,0.67881,0.97958, 0.,0.]
    qbar: [0    ,0.     ,0] # 13.143 ]
    g   : [0    ,0.     ,5.56   ]
#    v   : [0    ,0.6561,0.9690, 0.,0.]
#    qbar: [0.417,0.   , 9    ] #,-2.466,3.855]
#    g   : [0    ,0.   , 5.56 ] #,-2.074] #,1.824]

Q0: 1.378404875209022   #=sqrt(1.9)
alphas: 0.118 #0.100
fs:     0.3333333333333

MINUIT :
  Commands : |
    fix 111
    minimize
    hesse
    call fcn 3
#    fix 103 106 107 109 111 112 113 114 115 116 117 118 119 120 122

Evolution: QCDNUM
QCDNUM:
  xGrid   :   [9.9e-7, 0.01, 0.1, 0.4, 0.7]
  xGridW  :   [1,       2,     4,   8,  16]
  Q2Grid  :   [1.,  2.05e8 ]
  Q2GridW :   [1.,     1.]  
  NQ2bins :   120
  NXbins  :   200
  Read_QCDNUM_Tables : 1
  SplineOrder : 2
  ICheck  :   0

APPLgrid:  # APPLgrid specific
  muF: 1.0
  muR: 1.0
  Order: NLO   # APPLgrids are at max. NLO for now

Mz: 91.1876
Mw: 80.385
Mh: 125.9

Wz : 2.4952
Ww : 2.085
Wh : 1d-3
Wtp: 2.0d0

gf: 1.16638e-5
convFac: 0.389379338e9
alphaem: 7.29735e-3

sin2thW:  0.23127
Vud: 0.97427
Vus: 0.2254
Vub: 0.00358
Vcd: 0.22520
Vcs: 0.97344 
Vcb: 0.04156
Vtd: 0.00872
Vts: 0.04076
Vtb: 0.999133

# lepton masses:
men: 1e-10
mel: 0.510998928e-3
mmn: 1e-10
mmo: 0.1056583715
mtn: 1e-10
mta: 1.77682

# Light quark masses:
mup: 0.06983
mdn: 0.06983
mst: 0.150

# Heavy quark masses:
mch: 1.43 
mbt: 4.50
mtp: 173.0

# QCD parameters
Order : NLO
NFlavour : 5
