Minimizer: MINUIT # CERES
MINUIT:
  Commands: |
    set str 2
    call fcn 3
#    call fcn 1
#    migrad
#    hesse
#    call fcn 3
#  doErrors :  Hesse # None

DefaultEvolution: proton-LHAPDF

Evolutions:
  proton-LHAPDF:
    class: LHAPDF
#    set: "HERAPDF20_NNLO_EIG" # activate this to get chi2=0 at LO
#    set: "CT14nnlo"
    set: "NNPDF30_nlo_as_0118"
    member: 0

? !include constants.yaml

byReaction:
  # AFB settings:
  ? !include reactions/AFB/parameters.yaml
