Minimizer: MINUIT
MINUIT:
  Commands: |
    migrad
    call fcn 3
    
Parameters:
  ? !include reactions/Fractal_DISNC.yaml

? !include constants.yaml

hf_scheme_DISNC :
  defaultValue : 'Fractal_DISNC'  # Fractal model. Add parameters file if you want to try it (see above)
