Minimizer: MINUIT # CERES
MINUIT:
  Commands: |
    set str 2
    call fcn 3
#    call fcn 1
#    migrad
#    hesse
#    call fcn 3    
#  doErrors :  Hesse # None

#DefaultEvolution: proton-QCDNUM
DefaultEvolution: proton-LHAPDF

Evolutions:
  proton-QCDNUM:
    ? !include evolutions/QCDNUM/parameters.yaml
    # The following allows QCDNUM to read PDFs from other evolutions:
    EvolutionCopy: "proton-LHAPDF"
  proton-LHAPDF:
    class: LHAPDF
    set: "NNPDF30_nlo_as_0118"
    member: 0
  antiproton:
    class: FlipCharge
  neutron:
    class: FlipUD

? !include constants.yaml

# the two parameters below are not used: why one needs them with the present setup?
Q0 : 1.378404875209 # Initial scale =sqrt(1.9) 
alphas : 0.118

byReaction:
  # RT DIS scheme settings:
  ? !include reactions/RT_DISNC/parameters.yaml
  RT_DISNC:
    varin0 : 0.0
    varin1 : 1.0
    varin2 : -0.666666666667
    varin3 : 1.0        # recommended RT OPT settings
    evolution: proton-QCDNUM
  BaseDISCC:
    evolution: proton-QCDNUM
  # FONLL scheme settings:
  ? !include reactions/FONLL_DISNC/parameters.yaml
  ? !include reactions/FONLL_DISCC/parameters.yaml
  # FF ABM scheme settings:
  ? !include reactions/FFABM_DISNC/parameters.yaml
  ? !include reactions/FFABM_DISCC/parameters.yaml
  # AFB settings:
  ? !include reactions/AFB/parameters.yaml
  # APPLgrid settings:
  ? !include reactions/APPLgrid/parameters.yaml
  # (optional) Fractal module settings:
  ? !include reactions/Fractal_DISNC/parameters.yaml

# Specify HF scheme used for DIS NC processes:
hf_scheme_DISNC :
  defaultValue : 'RT_DISNC'        # global specification
#  defaultValue : 'BaseDISNC'       # global specification
#  defaultValue : 'FONLL_DISNC'     # global specification
#  defaultValue : 'FFABM_DISNC'
#  'HERA1+2 NCep 920' : 'BaseDISNC' # datafile specific (based on name)
#  1 : BaseDISNC
#  'HERA1+2 NCep 920' : 'Fractal_DISNC'  # Fractal model. Add parameters file if you want to try it (see above)

# Specify HF scheme used for DIS CC processes:
hf_scheme_DISCC :
  defaultValue : 'BaseDISCC'       # global specification
#  defaultValue : 'FONLL_DISCC'     # global specification
#  defaultValue : 'FFABM_DISCC'     # global specification

WriteLHAPDF6:
  name: "proton"
  description: "..."
  authors: "..."
  reference: "..."
    # use DefaultEvolution
  #evolution: proton-QCDNUM
    # take internal grid
  preferInternalGrid:
    # or define grid
  #Xrange: [1e-4, 1]
  #Qrange: [1,1000]
  #Xnpoints: 200
  #Qnpoints: 120
