Minimizer: MINUIT # CERES
MINUIT:
  Commands: |
    set str 2
    call fcn 1
    #migrad
    #hesse
    call fcn 3
#  doErrors :  Hesse # None

Parameters:
  Auv : [ 1.00000000, 0.00000000 ]
  Buv : [ 0.63144863, 0.02954405 ]
  Cuv : [ 4.84372279, 0.07646111 ]
  Duv : [ 0.00000000, 0.00000000 ]
  Euv : [ 17.47194527, 2.32145176 ]
  Adv : [ 1.00000000, 0.00000000 ]
  Bdv : [ 0.86165329, 0.06991674 ]
  Cdv : [ 4.44612054, 0.32714862 ]
  Ddv : [ 0.00000000, 0.00000000 ]
  Edv : [ 0.00000000, 0.00000000 ]
  Cubar : [ 7.61261199, 0.73394704 ]
  Dubar : [ 14.14712803, 2.85946815 ]
  Eubar : [ 0.00000000, 0.00000000 ]
  Adbar : [ 0.09408433, 0.00506237 ]
  Bdbar : [ -0.17987840, 0.00618488 ]
  Cdbar : [ 16.01409431, 3.86861456 ]
  Ddbar : [ 0.00000000, 0.00000000 ]
  Edbar : [ 0.00000000, 0.00000000 ]
  As : [ 0.07214400, 0.00000000 ]
  ZERO : [ 0.00000000, 0.00000000 ]
  BG_g_A : [ 1.00000000, 0.00000000 ]
  BG_g_B : [ 0.06463887, 0.05984238 ]
  BG_g_C : [ 7.12186012, 0.38089485 ]
  BG_g_F : [ 0.07917094, 0.02253926 ]
  BG_g_G : [ 0.00000000, 0.00000000 ]
  BG_g_H : [ 0.00000000, 0.00000000 ]
  mch : [ 1.23234263, 0.03121315, 1.00000000, 2.00000000 ]
  mbt : [ 3.97814400, 0.09746271, 3.00000000, 9.00000000 ]


Parameterisations:
  par_s:
    class: Expression
    expression: "Adbar*fs/(1-fs)*(x^Bdbar*(1-x)^Cdbar)"
  par_g:
    class: Expression
    expression: "BG_g_A * x^BG_g_B * (1 - x)^BG_g_C * (1 + BG_g_F * ln(x) + BG_g_G * ln(x)^2 + BG_g_H * ln(x)^3)"
  par_uv:
    class: Expression
    expression: "Auv*(x^Buv*(1-x)^Cuv)*(1+Duv*x+Euv*x^2)"
  par_dv:
    class: Expression
    expression: "Adv*(x^Bdv*(1-x)^Cdv)*(1+Ddv*x+Edv*x^2)"
  par_ubar:
    class: Expression
    expression: "Adbar*(x^Bdbar*(1-x)^Cubar)*(1+Dubar*x+Eubar*x^2)"
  par_dbar:
    class: Expression
    expression: "Adbar*(x^Bdbar*(1-x)^Cdbar)*(1+Ddbar*x+Edbar*x^2)"

DefaultDecomposition: proton
Decompositions:
  proton:
    class: UvDvUbarDbarS
    xuv: par_uv
    xdv: par_dv
    xubar: par_ubar
    xdbar: par_dbar
    xs: par_s
    xg: par_g

DefaultEvolution: proton-QCDNUM
#DefaultEvolution: proton-LHAPDF
Evolutions:
  proton-QCDNUM:
    ? !include evolutions/QCDNUM.yaml
    decomposition: proton #this could be omitted, as the default decomposition is set
    class: QCDNUM
    #xGrid   :   [9.9e-7, 0.01, 0.1, 0.4, 0.7]
    xGrid   :   [9.9e-9, 0.01, 0.1, 0.4, 0.7]
    xGridW  :   [1,       2,     4,   8,  16]
    Q2Grid  :   [1.,  2.05e8 ]
    Q2GridW :   [1.,     1.]
    NQ2bins :   120
    NXbins  :   200
    Read_QCDNUM_Tables : 1
    SplineOrder : 2
    ICheck  :   0                # do or not check of the grid boundaries,
  proton-LHAPDF:
    class: LHAPDF
    set: "CT10"
    member: 0

Q0 : 1.378404875209 # Initial scale =sqrt(1.9)

? !include constants.yaml

# AlphaS, incuding options to fit it:
alphas: 0.106
#  value: 0.118
#  step:  0.01
#  prior: 0.118
#  priorUnc: 0.1
#  min: 0.1
#  max: 0.3

# Strange and charm fractions:
fs: 0.4
fcharm: 0.

byReaction:
  FFABM_DISNC:
    ? !include reactions/FFABM_DISNC.yaml
    runm: 1
    ordfl: 0
    scalea1: 1.0
    scaleb1: 1.0
  FFABM_DISCC:
    ? !include reactions/FFABM_DISCC.yaml
    runm: 1
    ordfl: 0
    scalea1: 1.0
    scaleb1: 1.0
  # cbdiff (HVQMNR) settings
  cbdiff:
    #? !include reactions/cbdiff.yaml
    #debug: 1
    MS_MASS: 1
    precision: 0.65
    FragPar: 4.4 # charm
    hadronMass: 1.5 # charm
    mf_A: 1.0
    mf_B: 4.0
    mr_A: 1.0
    mr_B: 4.0
    steer_nf: 3

# Specify HF scheme used for DIS NC processes:
hf_scheme_DISNC :
#  defaultValue : 'RT_DISNC'        # global specification
#  defaultValue : 'BaseDISNC'       # global specification
#  defaultValue : 'FONLL_DISNC'     # global specification
  defaultValue : 'FFABM_DISNC'
#  'HERA1+2 NCep 920' : 'BaseDISNC' # datafile specific (based on name)
#  1 : BaseDISNC
#  'HERA1+2 NCep 920' : 'Fractal_DISNC'  # Fractal model. Add parameters file if you want to try it (see above)

# Specify HF scheme used for DIS CC processes:
hf_scheme_DISCC :
#  defaultValue : 'BaseDISCC'       # global specification
#  defaultValue : 'FONLL_DISCC'     # global specification
  defaultValue : 'FFABM_DISCC'     # global specification
